language: java
jdk: openjdk8

sudo: false
cache:
  directories:
  - "$HOME/.m2"
addons:
  apt:
    packages:
      - libxml2-utils

before_install:
  # Get Graylog version from Maven POM (property: "graylog.version")
  - export GRAYLOG_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="graylog.version"]/text()' pom.xml)
  # Checkout desired Graylog version
  - echo "Checking out Graylog ${GRAYLOG_VERSION}"
  - git clone --depth 1 --branch "${GRAYLOG_VERSION}" https://github.com/Graylog2/graylog2-server.git ../graylog2-server
  # Build Graylog web interface
  - pushd ../graylog2-server
  - mvn generate-resources -pl graylog2-server -B -V
  - popd

before_deploy:
  - rm -f target/original-*.jar
  - echo "Deploying release to GitHub releases..."
deploy:
  provider: releases
  api_key:
    secure: XNdHJ0YhiqWsR6+MoldKgxpseQQMFkbSGAbYWicARiaUnDqoaRCCPHboxDdfzx2EDKBOs3LiVA4eRafrg7ymzPV5xx7nEaB6kla2MxM8oJoIOMdMiiXgt2XSCpMsMllFykJpECc6IPr1Hqmt3Inh1e0BFcYRqM+u/05CgydcvnnLoxlP47EPmct0pBORrwRXKGqMegNwpygWfxJB2iSIGFUHW8UR40vWswVEOS1fcGfn5aAD2qPjnF9VQr170y0Eo3AVFGvpS1Dj5z0t5LxCEF0CPLs12vqhSSu4Y+G3/UwR+wwLBv9DX0A6JLA0xBCxbCwcrbhnH+hB5F1W35HkxGrepo6ZBYQdUPZw/qCuklQ7KAJMKULuK8pFV6AxThDZE8lNLduSbKsKIPutNUAHWvLYxLC+5G6lWAOvp6l81ORBjGFOPk6oErAsyIYVWrsF5f1nW6wnhnLpyHQjvwCeW9JhUtPt9eUkKaaiPbVDqqIieeCNJfIStmesxyvZTr/jmZTrZW+g2u5FARY6SFSjX39mafPCXGYbfrpqp39tdM4lnWkdEiSDRBtKh3TrXwDEgqlBM5UWUmFY1QSOAE/NHHhDXIUtM/v4FILYLDsA0UzvEdzKWtIRiiqrdUaw6LiPGQ4LVeYtqNM3igEKm6McJJ/QPBatA7/iCy+iFM/1JTs=
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  draft: true
  on:
    tags: true
    repo: irgendwr/TelegramAlert
