name: Close stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 5
        stale-issue-message: 'This issue was marked as stale because it has been open for 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-message: 'This pull request was marked as stale because it has been open for 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-label: 'no-stale'
